### PR TITLE
adding proper dcos_resolver for aws

### PR DESCRIPTION
**Pull request by bernadinm**
Related to https://jira.mesosphere.com/browse/DCOS-47983

Currently this causes a problem when applications need to perform `hostname -f`. This change will allow it to work.

### CODE REVIEW

**Review by geekbass — DISMISSED** [review]
LGTM

**Review by fatz — APPROVED** [review]
LGTM

**Review by fatz — CHANGES_REQUESTED** [review]
please have a look at jenkins README needs to be generated

**Review by fatz — CHANGES_REQUESTED** [review]
this will be a breaking change to existing clusters. 

So this cannot endup in a patch version as it needs further documentation and the user as do apply an update.

Lets consider a 0.2-pre branch getting this merged in

**Comment by bernadinm** [comment]
Thanks, @fatz! I've added this to the `release/v0.2` branch.

**Review by fatz — APPROVED** [review]
same as in dcos-terraform/terraform-gcp-dcos#22

**Pull request merged**
