### PR TITLE
add calico configurations

### PR DESCRIPTION
**Pull request by mainred**
This is basically a commit copy from https://github.com/dcos-terraform/terraform-aws-dcos/pull/77 which has been merged already.

### CODE REVIEW

**Comment by mainred** [comment]
The CI is red is because of, I think, ssh-agent in bootstrap node failing.
```
* module.dcos.module.dcos-core.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos: error executing "/tmp/terraform_1111988409.sh": Process exited with status 2
```

**Comment by fatz** [comment]
> The CI is red is because of, I think, ssh-agent in bootstrap node failing.
> 
> ```
> * module.dcos.module.dcos-core.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos: error executing "/tmp/terraform_1111988409.sh": Process exited with status 2
> ```

restarting CI lets see.

**Comment by mainred** [comment]
One out of 5 node failed for 
```
fatal: [172.12.0.7]: FAILED! => {"changed": false, "elapsed": 611, "msg": "timed out waiting for ping module test success: basic: the specified credentials were rejected by the server"}
```

**Comment by DominikDary** [comment]
@fatz Is the error related to the code change or the underlying infrastructure?

**Comment by mainred** [comment]
@fatz , more care please.

**Comment by fatz** [comment]
well its failing two time with the same error... it needs to be checked and reproduced.

**Comment by mainred** [comment]
@fatz , I created another [PR](https://github.com/dcos-terraform/terraform-azurerm-dcos/pull/27) which adds only one additional empty file,  and the CI failed for the same error above. This error seems not to be related to the calico configuration addition.

**Comment by fatz** [comment]
well that might be the case but I still need to investigate what is failing. Starting to investigate today

**Comment by fatz** [comment]
Was able to locally reproduce the issue. Working on a fix

**Pull request merged**
